// Estas son los idiomas en lista para que el usuario pueda escoger la traduccion



const countries = {
    
    "ar-SA": "Árabe",
    "sq-AL": "Albano",
    "de-DE": "Alemán",
    "be-BY": "Bielorrusia",
    "bem-ZM": "Bambara",
    "bn-IN": "Bengalí",
    "my-MM": "Burmese",
    "bs-BA": "Bosnia",
    "ca-ES": "Catalán",
    "cs-CZ": "Checo",
    "hr-HR": "Croata",
    "ko-KR": "Coreano",
    "da-DK": "Danés",
    "dz-BT": "Dzongkha",
    "es-ES": "Español",
    "et-EE": "Estonio",
    "sk-SK": "Eslovaco",
    "fi-FI": "Finés",
    "fr-FR": "Francés",
    "gu-IN": "Guyarati",
    "cy-GB": "Galés",
    "el-GR": "Griego",
    "he-IL": "Hebreo",
    "nl-NL": "Holandés",
    "hi-IN": "Hindi",
    "hu-HU": "Húngaro",
    "id-ID": "Indonesio",
    "is-IS": "Islandés",
    "it-IT": "Italiano",
    "en-GB": "Ingles",
    "ja-JP": "Japonés",
    "km-KM": "Jemer",
    "kk-KZ": "Kazajo",
    "kn-IN": "Kannada",
    "ku-TR": "Kurdish",
    "ky-KG": "Kyrgyz",
    "la-VA": "Latín",
    "lo-LA": "Lao",
    "lv-LV": "Letón",
    "dv-MV": "Maldivian",
    "ms-MY": "Malayo",
    "mt-MT": "Maltese",
    "ne-NP": "Nepalí",
    "no-NO": "Noruego",
    "fa-IR": "Persa",
    "ur-PK": "Pakistani",
    "ps-PK": "Pastún",
    "pl-PL": "Polaco",
    "pt-PT": "Portugués",
    "ro-RO": "Rumano",
    "ru-RU": "Ruso",
    "so-SO": "Somali",
    "sr-RS": "Serbio",
    "sv-SE": "Sueco",
    "sw-SZ": "Swahili",
    "ta-LK": "Tamil",
    "te-IN": "Telugu",
    "th-TH": "Tailandés",
    "tl-PH": "Tagalo",
    "tr-TR": "Turco",
    "uk-UA": "Ucraniano",
    "uz-UZ": "Uzbeko",
    "eu-ES": "Vasco",
    "vi-VN": "Vietnamita",
    "zu-ZA": "Zulu"
}